In [61]:
import pandas as pd
import numpy as np

In [62]:
df = pd.read_csv('BTP.csv')

In [63]:
df1 = df.drop('Subject', axis=1)

In [64]:
df2 = df1.drop('Hours taken to fall asleep', axis = 1)

In [80]:
df2.fillna(0, inplace=True)

In [102]:
df2.replace('         .', 0, inplace=True)

In [103]:
X = df2.iloc[:, :40]

In [104]:
X

Irritability  \
0             2.0   
1             0.0   
2             0.0   
3             3.0   
4             2.0   
..            ...   
912           2.0   
913           2.0   
914           0.0   
915           0.0   
916           0.0   

     Increased unnecessary whole body movements in specific situations  \
0                                                  2.0                   
1                                                  0.0                   
2                                                  0.0                   
3                                                  2.0                   
4                                                  0.0                   
..                                                 ...                   
912                                                0.0                   
913                                                0.0                   
914                                                0.0                   
915                                                2.0                   
916                                                0.0                   

     Difficulty concentrating on tasks or play activity independently  \
0                                                  0.0                  
1                                                  0.0                  
2                                                  2.0                  
3                                                  3.0                  
4                                                  0.0                  
..                                                 ...                  
912                                                0.0                  
913                                                0.0                  
914                                                0.0                  
915                                                0.0                  
916                                                0.0                  

     Difficulty concentrating on adult-directed tasks or play activities  \
0                                                  0.0                     
1                                                  0.0                     
2                                                  0.0                     
3                                                  2.0                     
4                                                  0.0                     
..                                                 ...                     
912                                                0.0                     
913                                                0.0                     
914                                                0.0                     
915                                                0.0                     
916                                                0.0                     

     Inattention  Fear about possible harm befalling major attachment figures  \
0            2.0                                                0.0             
1            0.0                                                2.0             
2            0.0                                                0.0             
3            2.0                                                0.0             
4            0.0                                                0.0             
..           ...                                                ...             
912          0.0                                                0.0             
913          0.0                                                0.0             
914          0.0                                                0.0             
915          2.0                                                0.0             
916          0.0                                                0.0             

     Fear about calamitous separation  Avoidance of being alone  \
0                                

In [105]:
y = df2.iloc[:, 40]

In [106]:
y

0      0
1      1
2      0
3      0
4      0
      ..
912    1
913    1
914    0
915    0
916    0
Name: GAD, Length: 917, dtype: int64

In [143]:
from sklearn.model_selection import train_test_split

In [144]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [107]:
df2.corr()['GAD']

Irritability                                                                                   0.134861
Increased unnecessary whole body movements in specific situations                              0.097303
Difficulty concentrating on tasks or play activity independently                               0.094650
Difficulty concentrating on adult-directed tasks or play activities                            0.100960
Inattention                                                                                    0.107533
Fear about possible harm befalling major attachment figures                                    0.169988
Fear about calamitous separation                                                               0.105794
Avoidance of being alone                                                                       0.233998
Anticipatory distress/resistance to separation                                                 0.073999
Withdrawal when attachement figure absent                       

In [108]:
df2

Irritability  \
0             2.0   
1             0.0   
2             0.0   
3             3.0   
4             2.0   
..            ...   
912           2.0   
913           2.0   
914           0.0   
915           0.0   
916           0.0   

     Increased unnecessary whole body movements in specific situations  \
0                                                  2.0                   
1                                                  0.0                   
2                                                  0.0                   
3                                                  2.0                   
4                                                  0.0                   
..                                                 ...                   
912                                                0.0                   
913                                                0.0                   
914                                                0.0                   
915                                                2.0                   
916                                                0.0                   

     Difficulty concentrating on tasks or play activity independently  \
0                                                  0.0                  
1                                                  0.0                  
2                                                  2.0                  
3                                                  3.0                  
4                                                  0.0                  
..                                                 ...                  
912                                                0.0                  
913                                                0.0                  
914                                                0.0                  
915                                                0.0                  
916                                                0.0                  

     Difficulty concentrating on adult-directed tasks or play activities  \
0                                                  0.0                     
1                                                  0.0                     
2                                                  0.0                     
3                                                  2.0                     
4                                                  0.0                     
..                                                 ...                     
912                                                0.0                     
913                                                0.0                     
914                                                0.0                     
915                                                0.0                     
916                                                0.0                     

     Inattention  Fear about possible harm befalling major attachment figures  \
0            2.0                                                0.0             
1            0.0                                                2.0             
2            0.0                                                0.0             
3            2.0                                                0.0             
4            0.0                                                0.0             
..           ...                                                ...             
912          0.0                                                0.0             
913          0.0                                                0.0             
914          0.0                                                0.0             
915          2.0                                                0.0             
916          0.0                                                0.0             

     Fear about calamitous separation  Avoidance of being alone  \
0                                

In [129]:
from tensorflow import keras as k

In [147]:
classifier = k.Sequential()

In [148]:
classifier.add(k.layers.Dense(22,  activation='relu', input_dim=40))

In [149]:
classifier.add(k.layers.Dense(22,activation='relu'))

In [150]:
classifier.add(k.layers.Dense(1, activation='sigmoid'))

In [151]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [135]:
import tensorflow as tf

In [152]:
X_train = np.asarray(X_train).astype(float)
X_test = np.asarray(X_test).astype(float)
y_train = np.asarray(y_train).astype(float)
y_test = np.asarray(y_test).astype(float)
X1 = X_train.astype(int)
y1 = y_train.astype(int)
X2 = X_test.astype(int)
y2 = y_test.astype(int)

In [153]:
classifier.fit(X1,y1,batch_size=10, epochs=100)

Epoch 1/100
69/69 [==============================] - 0s 1ms/step - loss: 1.2086 - accuracy: 0.6856
Epoch 2/100
69/69 [==============================] - 0s 1ms/step - loss: 0.6091 - accuracy: 0.7598
Epoch 3/100
69/69 [==============================] - 0s 1ms/step - loss: 0.5720 - accuracy: 0.7525
Epoch 4/100
69/69 [==============================] - 0s 1ms/step - loss: 0.5275 - accuracy: 0.7889
Epoch 5/100
69/69 [==============================] - 0s 1ms/step - loss: 0.4905 - accuracy: 0.7948
Epoch 6/100
69/69 [==============================] - 0s 1ms/step - loss: 0.4626 - accuracy: 0.8195
Epoch 7/100
69/69 [==============================] - 0s 1ms/step - loss: 0.4433 - accuracy: 0.8253
Epoch 8/100
69/69 [==============================] - 0s 1ms/step - loss: 0.4198 - accuracy: 0.8341
Epoch 9/100
69/69 [==============================] - 0s 1ms/step - loss: 0.4064 - accuracy: 0.8515
Epoch 10/100
69/69 [==============================] - 0s 1ms/step - loss: 0.3892 - accuracy: 0.8501
Epoch 11/

In [217]:
ypred = classifier.predict(X2)

In [218]:
ypred = ypred>0.65

In [176]:
ypred

array([[ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [

In [168]:
y2 = y2>0

In [169]:
y2

array([ True,  True, False, False, False, False,  True, False,  True,
       False, False, False, False, False, False, False, False,  True,
        True,  True, False,  True, False, False,  True, False, False,
       False, False, False, False,  True,  True, False, False, False,
        True, False, False, False, False,  True, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False,  True, False, False,  True,  True, False,
       False, False,  True, False, False, False, False,  True,  True,
       False,  True,  True, False, False, False,  True,  True,  True,
       False, False,  True,  True, False, False, False,  True,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False,

In [219]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y2,ypred)

In [220]:
cm

array([[153,  10],
       [ 41,  26]], dtype=int64)

0.717391304347826